package org.apache.cxf.hello_world_soap_http;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-07-09T20:34:10.500+09:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "http://cxf.apache.org/hello_world_soap_http", name = "Greeter")
@XmlSeeAlso({org.apache.cxf.hello_world_soap_http.types.ObjectFactory.class})
public interface Greeter {

    @WebMethod
    @RequestWrapper(localName = "greetMe", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types", className = "org.apache.cxf.hello_world_soap_http.types.GreetMe")
    @ResponseWrapper(localName = "greetMeResponse", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types", className = "org.apache.cxf.hello_world_soap_http.types.GreetMeResponse")
    @WebResult(name = "responseType", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types")
    public java.lang.String greetMe(

        @WebParam(name = "requestType", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types")
        java.lang.String requestType
    );

    @WebMethod
    @Oneway
    @RequestWrapper(localName = "greetMeOneWay", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types", className = "org.apache.cxf.hello_world_soap_http.types.GreetMeOneWay")
    public void greetMeOneWay(

        @WebParam(name = "requestType", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types")
        java.lang.String requestType
    );

    @WebMethod
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types", className = "org.apache.cxf.hello_world_soap_http.types.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types", className = "org.apache.cxf.hello_world_soap_http.types.SayHiResponse")
    @WebResult(name = "responseType", targetNamespace = "http://cxf.apache.org/hello_world_soap_http/types")
    public java.lang.String sayHi()
;
}
