
     CREATE TABLE BEARERACCESSTOKEN (
        TOKENKEY VARCHAR2(2000) NOT NULL,
         EXPIRESIN number(20) NOT NULL,
         ISSUEDAT number(20) NOT NULL,
         ISSUER VARCHAR2(255),
         REFRESHTOKEN VARCHAR2(255),
         TOKENTYPE VARCHAR2(255),
         CLIENTCODEVERIFIER VARCHAR2(255),
         GRANTCODE VARCHAR2(255),
         GRANTTYPE VARCHAR2(255),
         NONCE VARCHAR2(255),
         RESPONSETYPE VARCHAR2(255),
         CLIENT_CLIENTID VARCHAR2(255),
         SUBJECT_ID VARCHAR2(255),
         PRIMARY KEY (TOKENKEY)
     );

     CREATE TABLE BEARERACCESSTOKEN_AUDIENCES (
        BEARERACCESSTOKEN_TOKENKEY VARCHAR2(2000) NOT NULL,
         AUDIENCES VARCHAR2(255),
         AUDIENCES_ORDER INTEGER NOT NULL,
         PRIMARY KEY (BEARERACCESSTOKEN_TOKENKEY, AUDIENCES_ORDER)
     );

     CREATE TABLE BEARERACCESSTOKEN_EXTRAPROPERTIES (
        BEARERACCESSTOKEN_TOKENKEY VARCHAR2(2000) NOT NULL,
         EXTRAPROPERTIES VARCHAR2(255),
         EXTRAPROPNAME VARCHAR2(255) NOT NULL,
         PRIMARY KEY (BEARERACCESSTOKEN_TOKENKEY, EXTRAPROPNAME)
     );

     CREATE TABLE BEARERACCESSTOKEN_OAUTHPERMISSION (
        BEARERACCESSTOKEN_TOKENKEY VARCHAR2(2000) NOT NULL,
         SCOPES_PERMISSION VARCHAR2(255) NOT NULL
     );

     CREATE TABLE BEARERACCESSTOKEN_PARAMETERS (
        BEARERACCESSTOKEN_TOKENKEY VARCHAR2(2000) NOT NULL,
         PARAMETERS VARCHAR2(255),
         PROPNAME VARCHAR2(255) NOT NULL,
         PRIMARY KEY (BEARERACCESSTOKEN_TOKENKEY, PROPNAME)
     );

     CREATE TABLE CLIENT (
        CLIENTID VARCHAR2(255) NOT NULL,
         APPLICATIONDESCRIPTION VARCHAR2(255),
         APPLICATIONLOGOURI VARCHAR2(255),
         APPLICATIONLOGOUTURI VARCHAR2(255),
         APPLICATIONNAME VARCHAR2(255),
         APPLICATIONWEBURI VARCHAR2(255),
         CLIENTIPADDRESS VARCHAR2(255),
         CLIENTSECRET VARCHAR2(255),
         CONFIDENTIAL char(1) NOT NULL,
         HOMEREALM VARCHAR2(255),
         REGISTEREDAT number(20) NOT NULL,
         REGISTEREDDYNAMICALLY char(1) NOT NULL,
         TOKENENDPOINTAUTHMETHOD VARCHAR2(255),
         RESOURCEOWNERSUBJECT_ID VARCHAR2(255),
         SUBJECT_ID VARCHAR2(255),
         PRIMARY KEY (CLIENTID)
     );

     CREATE TABLE CLIENT_ALLOWEDGRANTTYPES (
        CLIENT_CLIENTID VARCHAR2(255) NOT NULL,
         ALLOWEDGRANTTYPES VARCHAR2(255),
         ALLOWEDGRANTTYPES_ORDER INTEGER NOT NULL,
         PRIMARY KEY (CLIENT_CLIENTID, ALLOWEDGRANTTYPES_ORDER)
     );

     CREATE TABLE CLIENT_APPLICATIONCERTIFICATES (
        CLIENT_CLIENTID VARCHAR2(255) NOT NULL,
         APPLICATIONCERTIFICATES VARCHAR2(255),
         APPLICATIONCERTIFICATES_ORDER INTEGER NOT NULL,
         PRIMARY KEY (CLIENT_CLIENTID, APPLICATIONCERTIFICATES_ORDER)
     );

     CREATE TABLE CLIENT_PROPERTIES (
        CLIENT_CLIENTID VARCHAR2(255) NOT NULL,
         PROPERTIES VARCHAR2(255),
         NAME VARCHAR2(255) NOT NULL,
         PRIMARY KEY (CLIENT_CLIENTID, NAME)
     );

     CREATE TABLE CLIENT_REDIRECTURIS (
        CLIENT_CLIENTID VARCHAR2(255) NOT NULL,
         REDIRECTURIS VARCHAR2(255),
         REDIRECTURIS_ORDER INTEGER NOT NULL,
         PRIMARY KEY (CLIENT_CLIENTID, REDIRECTURIS_ORDER)
     );

     CREATE TABLE CLIENT_REGISTEREDAUDIENCES (
        CLIENT_CLIENTID VARCHAR2(255) NOT NULL,
         REGISTEREDAUDIENCES VARCHAR2(255),
         REGISTEREDAUDIENCES_ORDER INTEGER NOT NULL,
         PRIMARY KEY (CLIENT_CLIENTID, REGISTEREDAUDIENCES_ORDER)
     );

     CREATE TABLE CLIENT_REGISTEREDSCOPES (
        CLIENT_CLIENTID VARCHAR2(255) NOT NULL,
         REGISTEREDSCOPES VARCHAR2(255),
         REGISTEREDSCOPES_ORDER INTEGER NOT NULL,
         PRIMARY KEY (CLIENT_CLIENTID, REGISTEREDSCOPES_ORDER)
     );

     CREATE TABLE OAUTHPERMISSION (
        PERMISSION VARCHAR2(255) NOT NULL,
         DEFAULTPERMISSION char(1) NOT NULL,
         DESCRIPTION VARCHAR2(255),
         INVISIBLETOCLIENT char(1) NOT NULL,
         PRIMARY KEY (PERMISSION)
     );

     CREATE TABLE OAUTHPERMISSION_HTTPVERBS (
        OAUTHPERMISSION_PERMISSION VARCHAR2(255) NOT NULL,
         HTTPVERBS VARCHAR2(255),
         HTTPVERBS_ORDER INTEGER NOT NULL,
         PRIMARY KEY (OAUTHPERMISSION_PERMISSION, HTTPVERBS_ORDER)
     );

     CREATE TABLE OAUTHPERMISSION_URIS (
        OAUTHPERMISSION_PERMISSION VARCHAR2(255) NOT NULL,
         URIS VARCHAR2(255),
         URIS_ORDER INTEGER NOT NULL,
         PRIMARY KEY (OAUTHPERMISSION_PERMISSION, URIS_ORDER)
     );

     CREATE TABLE REFRESHTOKEN (
        TOKENKEY VARCHAR2(2000) NOT NULL,
         EXPIRESIN number(20) NOT NULL,
         ISSUEDAT number(20) NOT NULL,
         ISSUER VARCHAR2(255),
         REFRESHTOKEN VARCHAR2(255),
         TOKENTYPE VARCHAR2(255),
         CLIENTCODEVERIFIER VARCHAR2(255),
         GRANTCODE VARCHAR2(255),
         GRANTTYPE VARCHAR2(255),
         NONCE VARCHAR2(255),
         RESPONSETYPE VARCHAR2(255),
         CLIENT_CLIENTID VARCHAR2(255),
         SUBJECT_ID VARCHAR2(255),
         PRIMARY KEY (TOKENKEY)
     );

     CREATE TABLE REFRESHTOKEN_ACCESSTOKENS (
        REFRESHTOKEN_TOKENKEY VARCHAR2(2000) NOT NULL,
         ACCESSTOKENS VARCHAR2(255),
         ACCESSTOKENS_ORDER INTEGER NOT NULL,
         PRIMARY KEY (REFRESHTOKEN_TOKENKEY, ACCESSTOKENS_ORDER)
     );

     CREATE TABLE REFRESHTOKEN_AUDIENCES (
        REFRESHTOKEN_TOKENKEY VARCHAR2(2000) NOT NULL,
         AUDIENCES VARCHAR2(255),
         AUDIENCES_ORDER INTEGER NOT NULL,
         PRIMARY KEY (REFRESHTOKEN_TOKENKEY, AUDIENCES_ORDER)
     );

     CREATE TABLE REFRESHTOKEN_EXTRAPROPERTIES (
        REFRESHTOKEN_TOKENKEY VARCHAR2(2000) NOT NULL,
         EXTRAPROPERTIES VARCHAR2(255),
         EXTRAPROPNAME VARCHAR2(255) NOT NULL,
         PRIMARY KEY (REFRESHTOKEN_TOKENKEY, EXTRAPROPNAME)
     );

     CREATE TABLE REFRESHTOKEN_OAUTHPERMISSION (
        REFRESHTOKEN_TOKENKEY VARCHAR2(2000) NOT NULL,
         SCOPES_PERMISSION VARCHAR2(255) NOT NULL
     );

     CREATE TABLE REFRESHTOKEN_PARAMETERS (
        REFRESHTOKEN_TOKENKEY VARCHAR2(2000) NOT NULL,
         PARAMETERS VARCHAR2(255),
         PROPNAME VARCHAR2(255) NOT NULL,
         PRIMARY KEY (REFRESHTOKEN_TOKENKEY, PROPNAME)
     );

     CREATE TABLE SERVERAUTHORIZATIONCODEGRANT (
        CODE VARCHAR2(255) NOT NULL,
         CODEVERIFIER VARCHAR2(255),
         REDIRECTURI VARCHAR2(255),
         AUDIENCE VARCHAR2(255),
         CLIENTCODECHALLENGE VARCHAR2(255),
         EXPIRESIN number(20) NOT NULL,
         ISSUEDAT number(20) NOT NULL,
         NONCE VARCHAR2(255),
         PREAUTHORIZEDTOKENAVAILABLE char(1) NOT NULL,
         RESPONSETYPE VARCHAR2(255),
         CLIENT_CLIENTID VARCHAR2(255),
         SUBJECT_ID VARCHAR2(255),
         PRIMARY KEY (CODE)
     );

     CREATE TABLE SERVERAUTHORIZATIONCODEGRANT_APPROVEDSCOPES (
        SERVERAUTHORIZATIONCODEGRANT_CODE VARCHAR2(255) NOT NULL,
         APPROVEDSCOPES VARCHAR2(255),
         APPROVEDSCOPES_ORDER INTEGER NOT NULL,
         PRIMARY KEY (SERVERAUTHORIZATIONCODEGRANT_CODE, APPROVEDSCOPES_ORDER)
     );

     CREATE TABLE SERVERAUTHORIZATIONCODEGRANT_EXTRAPROPERTIES (
        SERVERAUTHORIZATIONCODEGRANT_CODE VARCHAR2(255) NOT NULL,
         EXTRAPROPERTIES VARCHAR2(255),
         EXTRAPROPNAME VARCHAR2(255) NOT NULL,
         PRIMARY KEY (SERVERAUTHORIZATIONCODEGRANT_CODE, EXTRAPROPNAME)
     );

     CREATE TABLE SERVERAUTHORIZATIONCODEGRANT_REQUESTEDSCOPES (
        SERVERAUTHORIZATIONCODEGRANT_CODE VARCHAR2(255) NOT NULL,
         REQUESTEDSCOPES VARCHAR2(255),
         REQUESTEDSCOPES_ORDER INTEGER NOT NULL,
         PRIMARY KEY (SERVERAUTHORIZATIONCODEGRANT_CODE, REQUESTEDSCOPES_ORDER)
     );

     CREATE TABLE USERSUBJECT (
        ID VARCHAR2(255) NOT NULL,
         AUTHENTICATIONMETHOD INTEGER,
         LOGIN VARCHAR2(255),
         PRIMARY KEY (ID)
     );

     CREATE TABLE USERSUBJECT_PROPERTIES (
        USERSUBJECT_ID VARCHAR2(255) NOT NULL,
         PROPERTIES VARCHAR2(255),
         NAME VARCHAR2(255) NOT NULL,
         PRIMARY KEY (USERSUBJECT_ID, NAME)
     );

     CREATE TABLE USERSUBJECT_ROLES (
        USERSUBJECT_ID VARCHAR2(255) NOT NULL,
         ROLES VARCHAR2(255),
         ROLES_ORDER INTEGER NOT NULL,
         PRIMARY KEY (USERSUBJECT_ID, ROLES_ORDER)
     );
	 	 
	 CREATE TABLE SESSIONAUTHENTICITYTOKEN (
         SESSIONAUTHTOKEN VARCHAR2(255) NOT NULL,
         EXPIRESIN number(20),
		 CLIENT_CLIENTID VARCHAR2(255),
         SUBJECT_ID VARCHAR2(255) NOT NULL,
         PRIMARY KEY (SESSIONAUTHTOKEN)
     );

     ALTER TABLE BEARERACCESSTOKEN
        ADD CONSTRAINT BAT_CLT_CLIENTID
        FOREIGN KEY (CLIENT_CLIENTID)
        REFERENCES CLIENT;

     ALTER TABLE BEARERACCESSTOKEN
        ADD CONSTRAINT BAT_SUB_SUBJECTID
        FOREIGN KEY (SUBJECT_ID)
        REFERENCES USERSUBJECT;

     ALTER TABLE BEARERACCESSTOKEN_AUDIENCES
        ADD CONSTRAINT BAA_BAT_TOKENKEY
        FOREIGN KEY (BEARERACCESSTOKEN_TOKENKEY)
        REFERENCES BEARERACCESSTOKEN;

     ALTER TABLE BEARERACCESSTOKEN_EXTRAPROPERTIES
        ADD CONSTRAINT BAE_BAT_TOKENKEY
        FOREIGN KEY (BEARERACCESSTOKEN_TOKENKEY)
        REFERENCES BEARERACCESSTOKEN;

     ALTER TABLE BEARERACCESSTOKEN_OAUTHPERMISSION
        ADD CONSTRAINT BAO_OP_SCOPE
        FOREIGN KEY (SCOPES_PERMISSION)
        REFERENCES OAUTHPERMISSION;

     ALTER TABLE BEARERACCESSTOKEN_OAUTHPERMISSION
        ADD CONSTRAINT BAO_BAT_TOKENKEY
        FOREIGN KEY (BEARERACCESSTOKEN_TOKENKEY)
        REFERENCES BEARERACCESSTOKEN;

     ALTER TABLE BEARERACCESSTOKEN_PARAMETERS
        ADD CONSTRAINT BAP_BAT_TOKENKEY
        FOREIGN KEY (BEARERACCESSTOKEN_TOKENKEY)
        REFERENCES BEARERACCESSTOKEN;

     ALTER TABLE CLIENT
        ADD CONSTRAINT CLT_US_RSSUBJECT_ID
        FOREIGN KEY (RESOURCEOWNERSUBJECT_ID)
        REFERENCES USERSUBJECT;

     ALTER TABLE CLIENT
        ADD CONSTRAINT CLT_US_SUBJECT_ID
        FOREIGN KEY (SUBJECT_ID)
        REFERENCES USERSUBJECT;

     ALTER TABLE CLIENT_ALLOWEDGRANTTYPES
        ADD CONSTRAINT CLG_CLT_CLIENT_ID
        FOREIGN KEY (CLIENT_CLIENTID)
        REFERENCES CLIENT;

     ALTER TABLE CLIENT_APPLICATIONCERTIFICATES
        ADD CONSTRAINT CLA_CLT_CLIENT_ID
        FOREIGN KEY (CLIENT_CLIENTID)
        REFERENCES CLIENT;

     ALTER TABLE CLIENT_PROPERTIES
        ADD CONSTRAINT CLP_CLT_CLIENT_ID
        FOREIGN KEY (CLIENT_CLIENTID)
        REFERENCES CLIENT;

     ALTER TABLE CLIENT_REDIRECTURIS
        ADD CONSTRAINT CLR_CLT_CLIENT_ID
        FOREIGN KEY (CLIENT_CLIENTID)
        REFERENCES CLIENT;

     ALTER TABLE CLIENT_REGISTEREDAUDIENCES
        ADD CONSTRAINT CLRA_CLT_CLIENT_ID
        FOREIGN KEY (CLIENT_CLIENTID)
        REFERENCES CLIENT;

     ALTER TABLE CLIENT_REGISTEREDSCOPES
        ADD CONSTRAINT CLRS_CLT_CLIENT_ID
        FOREIGN KEY (CLIENT_CLIENTID)
        REFERENCES CLIENT;

     ALTER TABLE OAUTHPERMISSION_HTTPVERBS
        ADD CONSTRAINT OPH_OP_PERMISSION
        FOREIGN KEY (OAUTHPERMISSION_PERMISSION)
        REFERENCES OAUTHPERMISSION;

     ALTER TABLE OAUTHPERMISSION_URIS
        ADD CONSTRAINT OPU_OP_PERMISSION
        FOREIGN KEY (OAUTHPERMISSION_PERMISSION)
        REFERENCES OAUTHPERMISSION;

     ALTER TABLE REFRESHTOKEN
        ADD CONSTRAINT RT_CLT_CLIENT_ID
        FOREIGN KEY (CLIENT_CLIENTID)
        REFERENCES CLIENT;

     ALTER TABLE REFRESHTOKEN
        ADD CONSTRAINT RT_US_SUBJECT_ID
        FOREIGN KEY (SUBJECT_ID)
        REFERENCES USERSUBJECT;

     ALTER TABLE REFRESHTOKEN_ACCESSTOKENS
        ADD CONSTRAINT RTAT_RT_TOKENKEY
        FOREIGN KEY (REFRESHTOKEN_TOKENKEY)
        REFERENCES REFRESHTOKEN;

     ALTER TABLE REFRESHTOKEN_AUDIENCES
        ADD CONSTRAINT RTA_RT_TOKENKEY
        FOREIGN KEY (REFRESHTOKEN_TOKENKEY)
        REFERENCES REFRESHTOKEN;

     ALTER TABLE REFRESHTOKEN_EXTRAPROPERTIES
        ADD CONSTRAINT RTE_RT_TOKENKEY
        FOREIGN KEY (REFRESHTOKEN_TOKENKEY)
        REFERENCES REFRESHTOKEN;

     ALTER TABLE REFRESHTOKEN_OAUTHPERMISSION
        ADD CONSTRAINT RTO_OP_PERMISSION
        FOREIGN KEY (SCOPES_PERMISSION)
        REFERENCES OAUTHPERMISSION;

     ALTER TABLE REFRESHTOKEN_OAUTHPERMISSION
        ADD CONSTRAINT RTO_RT_TOKENKEY
        FOREIGN KEY (REFRESHTOKEN_TOKENKEY)
        REFERENCES REFRESHTOKEN;

     ALTER TABLE REFRESHTOKEN_PARAMETERS
        ADD CONSTRAINT RTP_RT_TOKENKEY
        FOREIGN KEY (REFRESHTOKEN_TOKENKEY)
        REFERENCES REFRESHTOKEN;

     ALTER TABLE SERVERAUTHORIZATIONCODEGRANT
        ADD CONSTRAINT SACG_CLT_CLIENT_ID
        FOREIGN KEY (CLIENT_CLIENTID)
        REFERENCES CLIENT;

     ALTER TABLE SERVERAUTHORIZATIONCODEGRANT
        ADD CONSTRAINT SACG_US_SUBJECT_ID
        FOREIGN KEY (SUBJECT_ID)
        REFERENCES USERSUBJECT;

     ALTER TABLE SERVERAUTHORIZATIONCODEGRANT_APPROVEDSCOPES
        ADD CONSTRAINT SACGA_SACG_CODE
        FOREIGN KEY (SERVERAUTHORIZATIONCODEGRANT_CODE)
        REFERENCES SERVERAUTHORIZATIONCODEGRANT;

     ALTER TABLE SERVERAUTHORIZATIONCODEGRANT_EXTRAPROPERTIES
        ADD CONSTRAINT SACGE_SACG_CODE
        FOREIGN KEY (SERVERAUTHORIZATIONCODEGRANT_CODE)
        REFERENCES SERVERAUTHORIZATIONCODEGRANT;

     ALTER TABLE SERVERAUTHORIZATIONCODEGRANT_REQUESTEDSCOPES
        ADD CONSTRAINT SACGR_SACG_CODE
        FOREIGN KEY (SERVERAUTHORIZATIONCODEGRANT_CODE)
        REFERENCES SERVERAUTHORIZATIONCODEGRANT;

     ALTER TABLE USERSUBJECT_PROPERTIES
        ADD CONSTRAINT USP_US_SUBJECT_ID
        FOREIGN KEY (USERSUBJECT_ID)
        REFERENCES USERSUBJECT;

     ALTER TABLE USERSUBJECT_ROLES
        ADD CONSTRAINT USR_US_SUBJECT_ID
        FOREIGN KEY (USERSUBJECT_ID)
        REFERENCES USERSUBJECT;
		
	ALTER TABLE SESSIONAUTHENTICITYTOKEN
        ADD CONSTRAINT SAT_CLT_CLIENTID
        FOREIGN KEY (CLIENT_CLIENTID)
        REFERENCES CLIENT;

     ALTER TABLE SESSIONAUTHENTICITYTOKEN
        ADD CONSTRAINT SAT_SUB_SUBJECTID
        FOREIGN KEY (SUBJECT_ID)
        REFERENCES USERSUBJECT;