
     ALTER TABLE BEARERACCESSTOKEN
        DROP CONSTRAINT BAT_CLT_CLIENTID ;

     ALTER TABLE BEARERACCESSTOKEN
        DROP CONSTRAINT BAT_SUB_SUBJECTID ;
       
    ALTER TABLE BEARERACCESSTOKEN_AUDIENCES
        DROP CONSTRAINT BAA_BAT_TOKENKEY ;

     ALTER TABLE BEARERACCESSTOKEN_EXTRAPROPERTIES
        DROP CONSTRAINT BAE_BAT_TOKENKEY ;

     ALTER TABLE BEARERACCESSTOKEN_OAUTHPERMISSION
        DROP CONSTRAINT BAO_OP_SCOPE ;

     ALTER TABLE BEARERACCESSTOKEN_OAUTHPERMISSION
        DROP CONSTRAINT BAO_BAT_TOKENKEY ;

     ALTER TABLE BEARERACCESSTOKEN_PARAMETERS
        DROP CONSTRAINT BAP_BAT_TOKENKEY ;

     ALTER TABLE CLIENT
        DROP CONSTRAINT CLT_US_RSSUBJECT_ID ;

     ALTER TABLE CLIENT
        DROP CONSTRAINT CLT_US_SUBJECT_ID ;

     ALTER TABLE CLIENT_ALLOWEDGRANTTYPES
        DROP CONSTRAINT CLG_CLT_CLIENT_ID ;

     ALTER TABLE CLIENT_APPLICATIONCERTIFICATES
        DROP CONSTRAINT CLA_CLT_CLIENT_ID ;

     ALTER TABLE CLIENT_PROPERTIES
        DROP CONSTRAINT CLP_CLT_CLIENT_ID ;

     ALTER TABLE CLIENT_REDIRECTURIS
        DROP CONSTRAINT CLR_CLT_CLIENT_ID ;

     ALTER TABLE CLIENT_REGISTEREDAUDIENCES
        DROP CONSTRAINT CLRA_CLT_CLIENT_ID ;

     ALTER TABLE CLIENT_REGISTEREDSCOPES
        DROP CONSTRAINT CLRS_CLT_CLIENT_ID ;

     ALTER TABLE OAUTHPERMISSION_HTTPVERBS
        DROP CONSTRAINT OPH_OP_PERMISSION ;

     ALTER TABLE OAUTHPERMISSION_URIS
        DROP CONSTRAINT OPU_OP_PERMISSION ;

     ALTER TABLE REFRESHTOKEN
        DROP CONSTRAINT RT_CLT_CLIENT_ID ;

     ALTER TABLE REFRESHTOKEN
        DROP CONSTRAINT RT_US_SUBJECT_ID ;

     ALTER TABLE REFRESHTOKEN_ACCESSTOKENS
        DROP CONSTRAINT RTAT_RT_TOKENKEY ;

     ALTER TABLE REFRESHTOKEN_AUDIENCES
        DROP CONSTRAINT RTA_RT_TOKENKEY ;

     ALTER TABLE REFRESHTOKEN_EXTRAPROPERTIES
        DROP CONSTRAINT RTE_RT_TOKENKEY ;

     ALTER TABLE REFRESHTOKEN_OAUTHPERMISSION
        DROP CONSTRAINT RTO_OP_PERMISSION ;

     ALTER TABLE REFRESHTOKEN_OAUTHPERMISSION
        DROP CONSTRAINT RTO_RT_TOKENKEY ;

     ALTER TABLE REFRESHTOKEN_PARAMETERS
        DROP CONSTRAINT RTP_RT_TOKENKEY ;

     ALTER TABLE SERVERAUTHORIZATIONCODEGRANT
        DROP CONSTRAINT SACG_CLT_CLIENT_ID ;

     ALTER TABLE SERVERAUTHORIZATIONCODEGRANT
        DROP CONSTRAINT SACG_US_SUBJECT_ID ;

     ALTER TABLE SERVERAUTHORIZATIONCODEGRANT_APPROVEDSCOPES
        DROP CONSTRAINT SACGA_SACG_CODE ;

     ALTER TABLE SERVERAUTHORIZATIONCODEGRANT_EXTRAPROPERTIES
        DROP CONSTRAINT SACGE_SACG_CODE ;

     ALTER TABLE SERVERAUTHORIZATIONCODEGRANT_REQUESTEDSCOPES
        DROP CONSTRAINT SACGR_SACG_CODE ;

     ALTER TABLE USERSUBJECT_PROPERTIES
        DROP CONSTRAINT USP_US_SUBJECT_ID ;

     ALTER TABLE USERSUBJECT_ROLES
        DROP CONSTRAINT USR_US_SUBJECT_ID ;
		
	ALTER TABLE SESSIONAUTHENTICITYTOKEN
        DROP CONSTRAINT SAT_CLT_CLIENTID ;

     ALTER TABLE SESSIONAUTHENTICITYTOKEN
        DROP CONSTRAINT SAT_SUB_SUBJECTID ;
