package org.apache.cxf.hello_world_soap_http;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-07-09T20:34:10.511+09:00
 * Generated source version: 3.3.7
 *
 */
@WebServiceClient(name = "GreeterService",
                  wsdlLocation = "classpath:wsdl/hello_world_wssec.wsdl",
                  targetNamespace = "http://cxf.apache.org/hello_world_soap_http")
public class CopyOfGreeterService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxf.apache.org/hello_world_soap_http", "GreeterService");
    public final static QName GreeterPort = new QName("http://cxf.apache.org/hello_world_soap_http", "GreeterPort");
    static {
        URL url = null;
        try {
            url = new URL("classpath:wsdl/hello_world_wssec.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CopyOfGreeterService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/hello_world_wssec.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CopyOfGreeterService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CopyOfGreeterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CopyOfGreeterService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CopyOfGreeterService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CopyOfGreeterService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CopyOfGreeterService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Greeter
     */
    @WebEndpoint(name = "GreeterPort")
    public Greeter getGreeterPort() {
        return super.getPort(GreeterPort, Greeter.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Greeter
     */
    @WebEndpoint(name = "GreeterPort")
    public Greeter getGreeterPort(WebServiceFeature... features) {
        return super.getPort(GreeterPort, Greeter.class, features);
    }

}
